version: "3.9"

services:
  payload:
    image: node:20.10.0-slim
    ports:
      - "3000:3000"
    environment:
      - PNPM_HOME=/pnpm
      - PATH=${PNPM_HOME}:${PATH}
    volumes:
      - /home/amin/.local/share/pnpm/store/v3:/pnpm
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm@8.12.1 && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - postgres-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "65432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres-network

volumes:
  data:
  node_modules:

networks:
  postgres-network:
    driver: bridge
